SOURCE ?= 1

.PHONY: all
all: format test build

.PHONY: format
format:
	clang-format src/* include/* -i

.PHONY: build
build:
	mkdir -p build
	cd build && \
	cmake -DSOURCE=$(SOURCE) -DCMAKE_CXX_FLAGS="-pg -O0" .. && \
	make

.PHONY: callgrind
callgrind:
	mkdir -p build_callgrind
	cd build_callgrind && \
	cmake -DSOURCE=$(SOURCE) -DCMAKE_CXX_FLAGS="-g -O0" .. && \
	make

.PHONY: debug
debug:
	mkdir -p build
	cd build && \
	cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-O0" -DSOURCE=$(SOURCE) .. && \
	make

.PHONY: clean
clean:
	rm -rf build
